

#Server
SERVER_PORT: 8081
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp-mail.outlook.com
EMAIL_PORT: 587
EMAIL_ID: peterson@petmaxtechnologies.com
EMAIL_PASSWORD: 0040105715@Petmax.com
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}