

#Server
SERVER_PORT: 8081
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: mail.kodsonplusltd.com
EMAIL_PORT: 587
EMAIL_ID: info@kodsonplusltd.com
EMAIL_PASSWORD: kds23#plus
VERIFY_EMAIL_HOST: http://192.168.88.27:${SERVER_PORT}