name: Build and Push Backend to Docker Hub

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.KODSON_DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.KODSON_DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t yourdockerhubusername/backend:latest .

      - name: Push Docker image to Docker Hub
        run: docker push yourdockerhubusername/backend:latest
